<?php

namespace DentalClinicBundle\Repository;

use DentalClinicBundle\Entity\ClinicBranch;

/**
 * ClinicBranchRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClinicBranchRepository extends \Doctrine\ORM\EntityRepository
{
//    public function getBranch(ClinicBranch $branch) {
//
//        $query = $this->createQueryBuilder('b')
//            ->where('b.name = :branch')
//            ->setParameter('branch',$branch)
//            ->getQuery()
//            ->getResult();
//
//        return $query;
//    }
}
