<?php

namespace DentalClinicBundle\Repository;

/**
 * ClinicBranchRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClinicBranchRepository extends \Doctrine\ORM\EntityRepository
{
}
