<?php

namespace DentalClinicBundle\Repository;

use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * MaterialRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MaterialRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param int $currentPage
     * @return \Doctrine\ORM\Tools\Pagination\Paginator
     */
    public function getAllMaterials($currentPage)
    {
        $query = $this->createQueryBuilder('m')
            ->orderBy('m.name', 'ASC')
            ->getQuery();

        $paginator = $this->paginate($query, $currentPage);

        return $paginator;
    }

    /**
     * @param \Doctrine\ORM\Query $dql
     * @param integer            $page
     * @param integer            $limit
     *
     * @return \Doctrine\ORM\Tools\Pagination\Paginator
     */
    public function paginate($dql, $page, $limit=10 )
    {
        $paginator = new Paginator($dql);

        $paginator->getQuery()
            ->setFirstResult($limit * ($page - 1))
            ->setMaxResults($limit);

        return $paginator;
    }
}
