<?php

namespace DentalClinicBundle\Repository;

use DentalClinicBundle\Entity\User;
use DentalClinicBundle\Entity\Visit;

/**
 * TariffRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TariffRepository extends \Doctrine\ORM\EntityRepository
{
//    /**
//     * @param Visit $visit |ArrayCollection
//     * @return mixed
//     */
//    public function sumEarnings($visit)
//    {
//        return $this->createQueryBuilder('t')
//            ->andWhere('t.visits = visit')
//            ->setParameters('visit', $visit->getManipulations())
//            ->select('SUM(t.price)')
//            ->getQuery()
//            ->getResult();
//    }
}
