<?php

namespace DentalClinicBundle\Repository;

use DentalClinicBundle\Entity\User;
use DentalClinicBundle\Entity\Visit;


/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
}
