<?php

namespace DentalClinicBundle\Repository;

use DentalClinicBundle\Entity\User;
use DentalClinicBundle\Entity\Visit;
use Doctrine\ORM\Tools\Pagination\Paginator;



/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param int $currentPage
     * @return \Doctrine\ORM\Tools\Pagination\Paginator
     */
    public function getAllUsers($currentPage)
    {
        $query = $this->createQueryBuilder('u')
            ->orderBy('u.fullName', 'ASC')
            ->getQuery();

        $paginator = $this->paginate($query, $currentPage);

        return $paginator;
    }

    /**
     * @param \Doctrine\ORM\Query $dql
     * @param integer            $page
     * @param integer            $limit
     *
     * @return \Doctrine\ORM\Tools\Pagination\Paginator
     */
    public function paginate($dql, $page, $limit=5 )
    {
        $paginator = new Paginator($dql);

        $paginator->getQuery()
            ->setFirstResult($limit * ($page - 1)) // Offset
            ->setMaxResults($limit); // Limit

        return $paginator;
    }
}
